package codes;
// Generated Sep 14, 2018 2:30:53 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TransactionTbl generated by hbm2java
 */
public class TransactionTbl  implements java.io.Serializable {


     private Integer trId;
     private int accountNo;
     private Date datetime;
     private Float amount;
     private Float balance;

    public TransactionTbl() {
    }

	
    public TransactionTbl(int accountNo) {
        this.accountNo = accountNo;
    }
    public TransactionTbl(int accountNo, Date datetime, Float amount, Float balance) {
       this.accountNo = accountNo;
       this.datetime = datetime;
       this.amount = amount;
       this.balance = balance;
    }
   
    public Integer getTrId() {
        return this.trId;
    }
    
    public void setTrId(Integer trId) {
        this.trId = trId;
    }
    public int getAccountNo() {
        return this.accountNo;
    }
    
    public void setAccountNo(int accountNo) {
        this.accountNo = accountNo;
    }
    public Date getDatetime() {
        return this.datetime;
    }
    
    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }
    public Float getAmount() {
        return this.amount;
    }
    
    public void setAmount(Float amount) {
        this.amount = amount;
    }
    public Float getBalance() {
        return this.balance;
    }
    
    public void setBalance(Float balance) {
        this.balance = balance;
    }




}


